version: "3.1"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password &&  --init-file /www/construcsur-app/BD/BDconstrucsurV2.sql   
        environment:
            MYSQL_DATABASE: construcsurV2
            MYSQL_PASSWORD: 4275
            MYSQL_ROOT_PASSWORD: 4275 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 4275
            MYSQL_ROOT_PASSWORD: 4274 
volumes:
    persistent:
